language: python
python:
  - "3.6"
env:
  - REPO=lyft/metadataproxy
sudo: required
services:
  - docker
before_install:
  - docker build -f Dockerfile -t $REPO:$TRAVIS_COMMIT .
install: "pip install -r requirements.txt"
script: make test
after_success:
  - ./docker_push.sh
deploy:
  provider: pypi
  user: lyftpypi
  password:
    secure: JdvBkBPCQ3y2Fpay7PD6Fruz2dhIWH2NJGp5THrzztF0VGUfg2zMeesOk5C1f80EhllH4qlZZMYLMEGHee+bGEl2zQMlJXz2fs45VDOo74xuQzhNKJDwFyRuucWx2aYwJ0wQLY1WgMpCFILtVN8g/OLPX0GUOwMD176HsCcclyaGKR8F35kPsuLjwDBToKlpwNjF5ka93sU4Ay1QwWTAcIjiXSuN43jR2lyWdnhRdej2ImDEEVXW1YFrtjM3BAMyGJW9cl6z4d9RMqo+sVNy/hjIwFtttBtP3o3oWbt3utzeXE2mP6d5Qg2HDK4sQSfFPN50p5SDv9k59mli7sXHqBlFU07gEQbshUV9hl+hL8TVNdQ3YSDai1MouWdIETYpu+S/x7M985GVTtkkCFSuOe69KHsycpuScExaLYWgm3JHClpTMSU9lbwXGSEPfgl+hNPMVuEGE9Op+skHXc8WxZt7j428uJnCLFGgaHM4b1hQbNU4zuz4wKKyTLK5OagcsY5t1joB/cd9G/9IZiVBjKEFdvzcL8mWaWFDEQgez4C9uPJ0wCqSfRqjo8pxmXNUDW/mwcQG6rg5HAjA2tnqpfMcq5TaKLVvfxixIe9zLRtxQfMHwzr4DuKL16PMfUH6JQ7lf51GrJbCsVzUYvkv4VeXXh3Umhx997lECg6qRB0=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: lyft/metadataproxy
    branch: pypipass2
